apiVersion: v1  
kind: PersistentVolume
metadata: 
  name: adguard-data 
  labels: 
    app: adguard
spec: 
  capacity: 
    storage: 1Gi 
  accessModes: 
  - ReadWriteMany 
  persistentVolumeReclaimPolicy: Retain 
  nfs: 
    path: /home/sistemas/mountpoints/adguard-data 
    server: 10.100.10.14 
    readOnly: false
