apiVersion: v1  
kind: PersistentVolume
metadata: 
  name: heimdall 
  labels: 
    app: heimdall
spec: 
  capacity: 
    storage: 1Gi 
  accessModes: 
  - ReadWriteMany 
  persistentVolumeReclaimPolicy: Retain 
  nfs: 
    path: /home/sistemas/mountpoints/heimdall
    server: 10.100.10.14 
    readOnly: false
