apiVersion: v1  
kind: PersistentVolume
metadata: 
  name: monit 
  labels: 
    app: monit
spec: 
  capacity: 
    storage: 1Gi 
  accessModes: 
  - ReadWriteMany 
  persistentVolumeReclaimPolicy: Retain 
  nfs: 
    path: /home/sistemas/mountpoints/monit
    server: 10.100.10.14 
    readOnly: false
